### ISSUE TITLE
Consider publishing the source code

### ISSUE THREAD

**Issue by opalenic** [slasher84/budgie#1]
First of all thanks a lot for creating this tool and helping with the F-15E situation.

Would you consider open sourcing the code? Maybe it's just my paranoia, but I don't feel comfortable running a random binary downloaded off the internet doing literal DLL injection. Thanks.

**Comment by slasher84** [comment]
It’s under consideration, if you’re not comfortable, use the system date change fix.

Virustotal.com analysis is in the release notes, note the Behavior tab.

**Comment by slasher84** [comment]
It’s also **NOT** doing DLL injection in mod form.

**Comment by slasher84** [comment]
[FAQ Item added addressing DLL Injection](https://github.com/slasher84/budgie/wiki#is-budgie-using-dll-injection)

Additional changes made to release notes to make it clear the Mod abandons the approach of DLL injection.

Apologies if you're getting bombarded with notifications on this @opalenic , just adding detail to explain the situation, ticket will remain open as you're not the first to request source release.

**Comment by opalenic** [comment]
Alright. Thanks for the info.

**Comment by slasher84** [comment]
All good, I went through and fixed up a lot of stuff that mentions DLL injection, only thing I can’t change is the Readme under 1.0.0.2 tag as it’s committed as part of the release which was admittedly rushed to discontinue injection and get Steam users flying.

First attempt at a public release, so apologies for any confusion.

**Comment by slasher84** [comment]
Decision made, no announcement at this time.

Open Source alternative StrikeRat by EagleEye uses similar, if less detail oriented approach.
